version: '3'
services:
  web:
    container_name: frontend
    build:
      context: ./.docker/frontend
      dockerfile: Dockerfile
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - nginx
      - api

  nginx:
    container_name: nginx
    build: ./.docker/backend/nginx
    ports:
      - 80:80
    volumes:
      - ./src/backend:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./.docker/backend/app
      dockerfile: Dockerfile
    environment:
      APP_NAME: 'SAMPLE'
      APP_ENV: 'development'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_DATABASE: 'laravel_development'
      DB_USERNAME: 'docker'
      DB_PASSWORD: 'docker'
      BROADCAST_DRIVER: 'log'
      QUEUE_CONNECTION: 'sync'
      SESSION_DRIVER: 'redis'
      SESSION_LIFETIME: '120'
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: 'null'
      REDIS_PORT: '6379'
      MAIL_MAILER: 'smtp'
      MAIL_HOST: 'mailhog'
      MAIL_PORT: '1025'
      MAIL_USERNAME: 'null'
      MAIL_PASSWORD: 'null'
      MAIL_ENCRYPTION: 'null'
      MAIL_FROM_ADDRESS: 'hello@example.com'
      MAIL_FROM_NAME: "${APP_NAME}"
    expose:
      - 9000
    volumes:
      - ./src/backend:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel_development'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
    volumes:
      - database:/var/lib/mysql
      - ./.docker/backend/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/backend/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  redis:
    image: redis:7.0-alpine
    container_name: redis
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - redis:/data
      - ./.docker/backend/redis/conf:/user/local/etc/redis
    ports:
      - 6379:6379

volumes:
  database:
  redis: