version: '3'
services:
  web:
    container_name: frontend
    build:
      context: ./.docker/frontend
      dockerfile: Dockerfile
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - nginx
      - api

  nginx:
    container_name: nginx
    build: ./.docker/backend/nginx
    ports:
      - 80:80
    volumes:
      - ./src/backend:/app
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./.docker/backend/app
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./src/backend:/app
    stdin_open: true
    tty: true
    restart: always
