version: '3'
services:
  web:
    container_name: frontend
    build:
      context: ./.docker/frontend
      dockerfile: Dockerfile
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend:/app
    stdin_open: true
    tty: true
    restart: always

  api:
    container_name: api
    build:
      context: ./.docker/backend/app
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./src/backend:/app
    stdin_open: true
    tty: true
    restart: always
